# Generated by Django 3.1.4 on 2021-01-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210104_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Wstawka', max_length=255),
        ),
    ]
